ElGanadero/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ElGanadero.Model;
using Ganadero.Interfaces.Interfaces;
using Ganadero.Model.Entidades;
using Validators.validatorsEntities;

 using  ElGanadero;


namespace ElGanadero.Controllers
{
    public class VentaController : Controller
    {

        GanaderoEntities4 context = null;
     
        private InterfaceProducto productorepo;
        private ventavalidator validator;
        private InterfaceVenta ventarepo;
        private InterfaceDetalle detallerepo;
         private InterfaceEntidadCliente entidadClirepo;
        
        
        public VentaController(ventavalidator validator, InterfaceProducto productorepo, InterfaceVenta ventarepo, InterfaceEntidadCliente entidadClirepo,InterfaceDetalle detallerepo)
        {
            this.productorepo = productorepo;
            this.ventarepo = ventarepo;
            this.validator = validator;
            this.detallerepo = detallerepo;
            this.entidadClirepo=entidadClirepo;
        }

        public ActionResult Index( string query="")
        {
            var dato = ventarepo.ByQueryAll(query);
            return View("Index",dato);
        }

     

        [HttpGet]
        public PartialViewResult Detalle(int id)
        {
            context = new GanaderoEntities4();

            return PartialView(context.DetalleVentas.Where(x => x.IdVentas == id).ToList());
        }



        [HttpGet]
        public ViewResult Create(string query="")
        {
            var cliente = entidadClirepo.All();
            ViewData["identiti"] = new SelectList(cliente, "id", "nombre");

            var dato = productorepo.ByQueryAll(query);
            return View("Create",dato);
        }
        [HttpGet]
        public PartialViewResult addproducto(int id, int index)
        {
            var producto = productorepo.Find(id);
            ViewBag.Index = index;
            return PartialView(producto);
        }


        [HttpPost]

        public ActionResult Create(Ganadero.Model.Entidades.Venta venta)
        {

            if (validator.Pass(venta))
            {

               ventarepo.Store(venta);

                TempData["UpdateSuccess"] = "la venta se a guardado correctamente";
                return RedirectToAction("index");
            }

            return View("create", venta);
        }

    }

    
}

ElGanadero/Views/Venta/Create.cshtml
<link rel="stylesheet" href="/Content/bootstrap.css">
@model List<Ganadero.Model.Entidades.Producto>
<h2 align="center">REALIZAR VENTA</h2>

@section styles{
    <style>
        .product {
            background-color: rgb(230,244,224);
        }
    </style>
}

@section scripts{
    <script>
        var index = 0;
        $(function aad() {
            $("#productos tbody tr").click(function () {
                $(this).addClass('product').siblings().removeClass('product');
                var id = this.cells[0].textContent;
                $.get('/Venta/addproducto/' + id + '?index=' + index).success(function (respuesta) {
                    $('#productoslis').append(respuesta);
                });
                index++;
            });
        });
    </script>
}


<div class="col-sm-8  col-md-offset-2">

    @if (TempData["UpdateSuccess"] != null)
    {
        <div class="alert alert-success">@TempData["UpdateSuccess"]</div>
    }
    </div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
 <form action="/Venta/Create" method="post">
     <div class="panel panel-info">
  <div class="panel-heading" style="text-align:center">
      <h4>Crear  venta</h4></div>
  <div class="panel-body">
  
  
        <div class="col-md-4" >
         <label for="fecha/">Fecha:</label>
        <input type="date" name="fecha" class="form-control" placeholder="AAAA/MM/DD"></imput>
        </div>

      <div class="col-md-3" >
            <label for="">Tipo Comprobante:</label>
        <select name="tipocomprobante" class="select form-control">
             <option value="Otros">--OTROS--</option>
            <option value="Boleta">Boleta</option>
            <option value="Factura">Factura</option>
        </select>
  </div>

    
     
     <div class="col-md-4">
        <label for="cliente">Cliente: </label>
        <div class="editor-field">
            @Html.DropDownList("identiti")
         @*   @Html.ValidationMessageFor(model => model.IdClasificacion)*@
            
        </div>
    </div>

    

  <form action="/venta/create" method="get">
       <div class="row">
           
        <div>
            <h2>Productos</h2>
        </div>
        <div class="row">
            <div class="col-md-6">
                <input type="text" align="center" name="query" class="form-control" placeholder="Buscar..." />
            </div>

            <div class="col-md-2">
                <button class="btn btn-primary" align="center">Buscar</button>
            </div>
        </div>
  


    <table id="productos" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre Producto</th>
                <th>Marca</th>
                <th>Precio</th>
                <th>Categoria</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.IdProducto</td>
                    <td>@item.NombreProducto </td>
                    <td>@item.Marca </td>
                    <td>@item.Precio</td>
                    <td>@item.categoria.Descripcion</td>

                    <td>
                        <a href="#" onclick="aad()">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                            Agregar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div>
    </div>
    <div>
        <h2>Lista Productos</h2>
    </div>

    <table id="listaproductos"   name="detalle" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre Producto</th>
                <th>Marca</th>
                <th>PrecioUni</th>
                <th>Categoria</th>
                <th>cantidad</th>
                <th>precioTo</th>

            </tr>
        </thead>
        <tbody id="productoslis">
        </tbody>
        
    </table>
    <div class="col-md-4">
                <input type="text"  name="total" class="form-control" placeholder="TotalPagar" />
            </div>
   <br />
     <br />
     <br />
    <div >
   
    </div>

      <nav>
  <ul class="pager">
     <button class="btn btn-primary glyphicon glyphicon-floppy-saved">Guardar</button>

              <a href="/venta/index" class="btn btn-danger">
                <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                cancelar
            </a>
  </ul>
</nav>
       </form>
</div>
   </div>
 

ElGanadero/Views/Venta/Detalle.cshtml
<link rel="stylesheet" href="/Content/bootstrap.css">
@model List<ElGanadero.Model.DetalleVenta>
   <div class="panel panel-info">
  <div class="panel-heading" style="text-align:center">
      <h4> detalle de venta</h4></div>
  <div class="panel-body">
<table class="table" id="master">
    <thead>
        <tr>
            <th>Idventa</th>
            <th>producto nombre</th>
            <th>catidad</th>
            <th>precio</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.IdVentas</td>
                <td>@item.Producto.NombreProducto </td>
                <td>@item.cantidad</td>
                 <td>@item.preciodeta</td>
            </tr>
        }
    </tbody>
</table>
      </div>
       </div>

ElGanadero/Views/Venta/DevolucionOcambio.cshtml
@{
    ViewBag.Title = "DevolucionOcambio";
}

<h2>DevolucionOcambio</h2>

ElGanadero/Views/Venta/addproducto.cshtml
<tr>

   <td><input type="hidden" name="detalleventa[@ViewBag.Index].IdProducto" value="@Model.IdProducto" /></td>
    <td>@Model.NombreProducto</td>
    <td>@Model.Marca</td>
    <td>@Model.Precio</td>
    <td>@Model.categoria.Descripcion</td>
    
    <td><input type="text" name="detalleventa[@ViewBag.Index].Cantidad" /></td>
     <td><input type="hidden" name="detalleventa[@ViewBag.Index].NombreProducto" value="@Model.NombreProducto" /></td>
     <td><input type="hidden" name="detalleventa[@ViewBag.Index].preciodeta" value="@Model.Precio*catidad" /></td>
     <td><input type="hidden" name="detalleventa[@ViewBag.Index].IDCategoria" value="@Model.IDCategoria" /></td>
   
</tr>  

ElGanadero/Views/Venta/index.cshtml
<link rel="stylesheet" href="/Content/bootstrap.css">
@*@model List<Ganadero.Model.Entidades.Venta>*@

@section styles{
    <style>
        .product {
            background-color: rgb(230,244,224);
        }
    </style>
}

@section scripts{
    <script>
        var index = 0;
        $(function () {
            $("#master tbody tr").click(function () {
                $(this).addClass('product').siblings().removeClass('product');
                var id = this.cells[0].textContent;
                getventaID(id);
                //$.get('/Venta/addproducto/' + id + '?index=' + index).success(function (respuesta) {
                //    $('#productoslis').append(respuesta);
                //});
                //index++;
            });
            function getventaID(ventaid)
            {
                $.ajax({
                    url: 'venta/getventaID',
                    type:'GET',
                    data: { id: ventaid },

                    error: function (ex) {
                        alert(ex.responseText);
                    },
                    success: function (response)
                    {

                    }


                });
            }


        });
    </script>
    }





<h2 align="center">lista  de Ventas</h2>
<div class="col-sm-12  col-md-offset-0" >

@if (TempData["UpdateSuccess"] != null)
{
    <div class="alert alert-success">@TempData["UpdateSuccess"]</div>
}


   <div class="panel panel-info">
  <div class="panel-heading" style="text-align:center">
      <h4> ventas</h4></div>
  <div class="panel-body">

<form action="/venta/index" method="get">

    <div class="row" >
        <div class="col-md-6">
            <input type="text"name="query" class="form-control" placeholder="Buscar..." />
        </div>
       
        <div class="col-md-2">
            <button class="btn btn-primary"align="center">Buscar</button>
        </div>
         <div class="col-md-2">
            <a href="/venta/Create" class="btn btn-success" style="    margin-bottom: 10px;">Crear</a>
        </div>
    </div>
</form>


<table class="table" id="master">
    <thead>
        <tr>
            <th>Id</th>
            <th>tipo comprobante</th>
            <th>fecha</th>
            <th>total</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ventaID</td>
                <td>@item.tipocomprobante </td>
                <td>@item.fecha </td>
               
               <td>@Ajax.ActionLink("cambio", "Detalle", "Venta", new { id=item.ventaID}, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "detalle" })

               </td>
                <td>
                    <a href="/Producto/Editar/@item.ventaID" class="glyphicon glyphicon-pencil">Editar</a> |
                  
                </td>
            </tr>
        }
    </tbody>
</table>
     <h3> detalle venta</h3>
      <div id="detalle">    </div>
      </div>
       </div>
    </div>